export const BASE_URL = "http://69.57.172.140";

export const columns = ["Accounts"];

export const rowData = [
  "account",
  "magic_number",
  "avg_lose",
  "avg_lose_pips",
  "avg_net_pips",
  "avg_trade",
  "avg_trade_time",
  "avg_win",
  "avg_win_pips",
  "best_trade",
  "consecutive_lose_trades",
  "consecutive_losses",
  "consecutive_profits",
  "consecutive_win_trades",
  "gross_loss",
  "gross_profit",
  "longest_trade",
  "longest_trade_time",
  "lose_percentage",
  "losers_count",
  // 'magic_number',
  "net_pips",
  "net_profit",
  "profit_factor",
  "shortest_trade",
  "shortest_trade_time",
  "total_lose_pips",
  "total_win_pips",
  "trades_count",
  "win_percentage",
  "winners_count",
  "worst_trade",
];

export const ALL_TRADES_HEADER = [
  "account",
  "close_price",
  "close_time",
  "comment",
  "commission",
  "id",
  "lots",
  "magic_number",
  "open_price",
  "open_time",
  "order_id",
  "order_type",
  "pnl",
  "sl",
  "swap",
  "symbol",
  "tp",
];

export const TOP_EA_COLUMNS = [
  // { id: "account", label: "Account" },
  { id: "magic_number", label: "Magic Number" },
  { id: "trades_count", label: "No of Trades" },
  { id: "gross_profit", label: "Gross Profit" },
  { id: "gross_loss", label: "Gross Loss" },
  { id: "net_profit", label: "Net Profit" },
  { id: "profit_factor", label: "Profit Factor" },
  { id: "winners_count", label: "Winners" },
  { id: "losers_count", label: "Losers" },
  { id: "win_percentage", label: "Win Percentage" },
  { id: "lose_percentage", label: "Loss Percentage" },
  { id: "avg_win", label: "Avg Win" },
  { id: "avg_lose", label: "Avg Loss" },
  { id: "avg_trade", label: "Avg Trade" },
  { id: "best_trade", label: "Best Trade" },
  { id: "worst_trade", label: "Worst Trade" },
  { id: "longest_trade", label: "Longest Trade" },
  { id: "shortest_trade", label: "Shortest Trade" },
  { id: "avg_trade_time", label: "Avg Trade Time" },
  { id: "total_win_pips", label: "Total Win Pips" },
  { id: "total_lose_pips", label: "Total Loss Pips" },
  { id: "net_pips", label: "Net Pips" },
  { id: "avg_win_pips", label: "Avg Win Pips" },
  { id: "avg_lose_pips", label: "Avg Loss Pips" },
  { id: "avg_net_pips", label: "Avg Net Pips" },
  { id: "consecutive_win_trades", label: "Consecutive Win Trades" },
  { id: "consecutive_lose_trades", label: "Consecutive Loss Trades" },
  { id: "consecutive_profits", label: "Consecutive Profits" },
  { id: "consecutive_losses", label: "Consecutive Losses" },
];

export const HIGHLIGHTED_COLUMNS = [
  "avg_lose",
  "avg_lose_pips",
  "avg_net_pips",
  "avg_trade",
  "best_trade",
  "gross_loss",
  "worst_trade",
  "total_lose_pips",
  "net_pips",
  "consecutive_losses",
];

export const ACCOUNT_PATH = "ACCOUNT_PAGE";
export const MAGIC_NUMBER_PATH = "MAGIC_NUMBER_PAGE";
export const ALL_TRADES_PATH = "ALL_TRADES_PAGE";
